package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/tiancaiamao/ai/internal/evolvemini"
)

func runPR(genDir string) error {
	// Find best generation
	records, err := loadGenerationRecords(genDir)
	if err != nil {
		return err
	}

	if len(records) == 0 {
		return fmt.Errorf("no generation records found")
	}

	// Find the generation with best score
	var bestGen *evolvemini.GenerationRecord
	for i := range records {
		if records[i].SuiteScore == nil {
			continue
		}
		if bestGen == nil || records[i].SuiteScore.WeightedAverage > bestGen.SuiteScore.WeightedAverage {
			bestGen = &records[i]
		}
	}

	if bestGen == nil {
		return fmt.Errorf("no scored generations found")
	}

	fmt.Printf("=== Best Generation %d ===\n", bestGen.Generation)
	fmt.Printf("Score: %.1f\n", bestGen.SuiteScore.WeightedAverage)
	fmt.Printf("Worktree: gen_%d\n", bestGen.Generation)
	fmt.Printf("Path: %s\n", filepath.Join(genDir, fmt.Sprintf("gen_%d", bestGen.Generation)))

	// Create PR using gh CLI
	worktreePath := filepath.Join(genDir, fmt.Sprintf("gen_%d", bestGen.Generation))
	prBranch := fmt.Sprintf("evolve-mini/gen-%d", bestGen.Generation)
	prTitle := fmt.Sprintf("Optimize compact: Gen %d (score %.1f)", bestGen.Generation, bestGen.SuiteScore.WeightedAverage)

	// Generate PR body
	worstCount := 3
	if len(bestGen.SuiteScore.WorstCaseIDs) < worstCount {
		worstCount = len(bestGen.SuiteScore.WorstCaseIDs)
	}

	prBody := fmt.Sprintf("This PR contains optimized compact code from evolution generation %d.\n\nScore: %.1f\n\nChanges:\n- %d improvements\n- Best cases: %s\n- Worst casess: %d\n\nGenerated by evolve-mini framework.",
		bestGen.Generation,
		bestGen.SuiteScore.WeightedAverage,
		strconv.Itoa(bestGen.SuiteScore.ImprovedCases),
		strings.Join(bestGen.SuiteScore.BestCaseIDs, ", "),
		worstCount)

	fmt.Println("Creating PR...")
	fmt.Printf("  Branch: %s\n", prBranch)
	fmt.Printf("  Title: %s\n", prTitle)
	fmt.Printf("  Target: main\n")

	// Create PR branch (checkout from worktree)
	cmd := exec.Command("git", "checkout", "-b", prBranch, "HEAD")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("create PR branch: %w\n%s", err, output)
	}

	// Stage changes from worktree
	cmd = exec.Command("git", "add", "-A")
	cmd.Dir = worktreePath
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("stage changes: %w\n%s", err, output)
	}

	// Commit with message
	commitMsg := fmt.Sprintf("evolve-mini: gen %d - %s\nScore: %.1f",
		bestGen.Generation,
		bestGen.OptimizeRationale,
		bestGen.SuiteScore.WeightedAverage)

	cmd = exec.Command("git", "commit", "-m", commitMsg)
	cmd.Dir = worktreePath
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("commit: %w\n%s", err, output)
	}

	// Switch back to main
	cmd = exec.Command("git", "checkout", "main")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("checkout main: %w\n%s", err, output)
	}

	// Create PR using gh CLI
	cmd = exec.Command("gh", "pr", "create",
		"--title", prTitle,
		"--body", prBody,
		"--base", "main",
		"--head", prBranch)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("create PR: %w\n%s", err, output)
	}

	fmt.Printf("\n✓ PR created!\n")

	return nil
}

func loadGenerationRecords(genDir string) ([]evolvemini.GenerationRecord, error) {
	// Load all generation records
	records := []evolvemini.GenerationRecord{}

	entries, err := os.ReadDir(genDir)
	if err != nil {
		return nil, err
	}

	for _, e := range entries {
		if e.IsDir() {
			recordPath := filepath.Join(genDir, e.Name(), "generation_record.json")
			data, err := os.ReadFile(recordPath)
			if err != nil {
				continue
			}
			var record evolvemini.GenerationRecord
			if err := json.Unmarshal(data, &record); err != nil {
				continue
			}
			records = append(records, record)
		}
	}

	return records, nil
}